cat_items:
  - name: "baseball hat"
    description: "a loose fitting hat"
    price: 20
    available_to_buy: true
    bonuses:
      - "+5 speed"
      - "+1 friendly"
      - "+2 baseball"
  - name: "big catnip cigar"
    available_to_buy: true
    description: "this is a comically large catnip cigar. too bad you forgot your matches"
    price: 10
    bonuses:
      - "-1 smell"
  - name: "giant inflatable rat"
    available_to_buy: false
    description: "I think this belongs to the Mouser's Local 402 Union"
    price: 999
    bonuses:
      - "+5 solidarity"
  - name: "mysterious parasol"
    available_to_buy: true
    description: "Sure it blocks the shade, but in a kind of haunted spooky way. oh well!"
    price: 115
    bonuses:
      - "+2 intrigue"
      - "+4 shade"
spot_items:
  - name: "blue spotted blanket"
    description: "say goodbye to sandy butts"
    price: 22
    available_to_buy: true
    bonuses:
      - "-2 sandy beans"
  - name: "folding chair"
    description: "a moderately comfortable folding chair"
    price: 40
    available_to_buy: true
    bonuses:
      - "+1 afternoon nap"
  - name: "plastic cooler"
    description: "no drinks or ice, but a box is a box"
    price: 60
    available_to_buy: true
    bonuses:
      - "+4 i'm in a box"
  - name: "bit of cellophane"
    description: "I think this is from a Chunky bar wrapper"
    price: 5
    available_to_buy: true
    bonuses:
      - "+6 entertainment"
