items:
  - name: "baseball hat"
    description: "a loose fitting hat"
    price: 20
    available_to_buy: true
    bonuses:
      - "+5 speed"
      - "+1 friendly"
      - "+2 baseball"
  - name: "big catnip cigar"
    available_to_buy: true
    description: "this is a comically large catnip cigar. too bad you forgot your matches"
    price: 10
    bonuses:
      - "-1 smell"
  - name: "giant inflatable rat"
    available_to_buy: false
    description: "I think this belongs to the Mouser's Local 402 Union"
    price: 999
    bonuses:
      - "+5 solidarity"
  - name: "mysterious parasol"
    available_to_buy: true
    description: "Sure it blocks the shade, but in a kind of haunted spooky way. oh well!"
    price: 115
    bonuses:
      - "+2 intrigue"
      - "+4 shade"
